version: '3.7'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: pwd
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  api:
    build: ./api/express
    container_name: api_service
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  front_admin:
    build: ./front_admin/admin
    container_name: admin_frontend
    restart: always
    ports:
      - "8080:8080"
    networks:
      - my_network

  front_users:
    build: ./front_users/user
    container_name: users_frontend
    restart: always
    ports:
      - "8081:8081"
    networks:
      - my_network    

  reverse_proxy:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    networks:
      - my_network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - front_admin
      - front_users

networks:
  my_network:
